export const CLIENT_ACCOUNTS = [
  { vps: "VPS 1", booker: "PokerStars", status: "ON", balance: 124.66, currency: "USD" },
  { vps: "VPS 1", booker: "1win", status: "ON", balance: 143.35, currency: "USDT" },
  { vps: "VPS 1", booker: "Melbet", status: "TMP", balance: 500, currency: "USD" },
  { vps: "VPS 1", booker: "BetFury", status: "ON", balance: 14.22, currency: "USDT" },
  { vps: "VPS 1", booker: "Gamdom", status: "ON", balance: 105.13, currency: "USD" },
  { vps: "VPS 2", booker: "Pinnacle", status: "ON", balance: 167.67, currency: "USD" },
  { vps: "VPS 2", booker: "PokerStars", status: "ON", balance: 573.63, currency: "USD" },
  { vps: "VPS 2", booker: "BetFury", status: "ON", balance: 78.21, currency: "USDT" },
  { vps: "VPS 2", booker: "Shuffle", status: "ON", balance: 3.07, currency: "USDT" },
  { vps: "VPS 2", booker: "Polymarket", status: "ON", balance: 193.59, currency: "USDT" },
  { vps: "VPS 2", booker: "Sportsbetio", status: "ON", balance: 109.47, currency: "USDT" },
  { vps: "VPS 2", booker: "Kalshi", status: "ON", balance: 101.71, currency: "USDT" },
  { vps: "VPS 2", booker: "ArtLine", status: "ON", balance: 0.22, currency: "USDT" },
  { vps: "VPS 2", booker: "Gamdom", status: "ON", balance: 5.96, currency: "USD" },
  { vps: "VPS 2", booker: "BC.Game", status: "ON", balance: 125.73, currency: "USD" },
  { vps: "VPS 2", booker: "Betdex", status: "ON", balance: 119.99, currency: "USD" },
  { vps: "VPS 2", booker: "Vavada", status: "ON", balance: 303.29, currency: "USD" },
  { vps: "VPS 2", booker: "888sport", status: "ON", balance: 41.89, currency: "USD" },
  { vps: "VPS 2", booker: "BetOnline", status: "ON", balance: 39.82, currency: "USD" },
  { vps: "VPS 2", booker: "Cloudbet", status: "ON", balance: 124.58, currency: "USDT" },
  { vps: "VPS 2", booker: "Betway", status: "ON", balance: 111.31, currency: "USD" },
  { vps: "VPS 3", booker: "1win", status: "ON", balance: 101.67, currency: "USDT" },
  { vps: "VPS 3", booker: "Melbet", status: "ON", balance: 66.38, currency: "USDT" },
  { vps: "VPS 3", booker: "BetFury", status: "ON", balance: 158.08, currency: "USDT" },
  { vps: "VPS 3", booker: "Gamdom", status: "ON", balance: 104.02, currency: "USD" },
  { vps: "VPS 3", booker: "BetOnline", status: "OFF", balance: 0, currency: "USD", note: "Internal Error | Betonline" },
  { vps: "VPS 3", booker: "ArtLine", status: "ON", balance: 229.95, currency: "USDT" },
  { vps: "VPS 4", booker: "1xBit", status: "ON", balance: 0, currency: "USDT" },
  { vps: "VPS 4", booker: "1win", status: "ON", balance: 102.13, currency: "USDT" },
  { vps: "VPS 4", booker: "Gamdom", status: "ON", balance: 229.29, currency: "USD" },
  { vps: "VPS 4", booker: "BC.Game", status: "ON", balance: 72.23, currency: "USD" },
  { vps: "VPS 4", booker: "BetOnline", status: "ON", balance: 7.89, currency: "USD" },
  { vps: "VPS 4", booker: "Kalshi", status: "PRE MARKET", balance: 100, currency: "USDT" },
  { vps: "VPS 4", booker: "Polymarket", status: "PRE MARKET", balance: 100, currency: "USDT" },
  { vps: "VPS 4", booker: "SXBET", status: "PRE MARKET", balance: 0, currency: "USDT" },
  { vps: "VPS 2", booker: "Jackbit", status: "ON", balance: 27.74, currency: "USDT" },
  { vps: "VPS 2", booker: "Jack", status: "OFF", balance: 0, currency: "USDT" },
  { vps: "VPS 5", booker: "1xBet", status: "ON", balance: 112.99, currency: "USD" },
  { vps: "VPS 5", booker: "1win", status: "ON", balance: 0, currency: "USDT" },
  { vps: "VPS 5", booker: "Jack", status: "OFF", balance: 0, currency: "USDT.ERC20", note: "Jack getWallets response no JSON" },
  { vps: "VPS 5", booker: "Sportsbetio", status: "OFF", balance: 0, currency: "USDT", note: "Falta sportsbetio.cookie/cookies o SPORTSBETIO_COOKIE para consultar balance" },
  { vps: "VPS 5", booker: "BetFury", status: "ON", balance: 130, currency: "USDT" },
  { vps: "VPS 5", booker: "Stake", status: "ON", balance: 123.84, currency: "USDT" }
].map((account) => ({
  ...account,
  id: `${account.vps}-${account.booker}`.toLowerCase().replace(/[^a-z0-9]+/g, "-")
}));

export const ACTIVE_CLIENT_COUNT = CLIENT_ACCOUNTS.filter(
  (account) => account.status === "ON"
).length;
