export const CLIENT_ACCOUNTS = [
  { vps: "VPS 1", booker: "PokerStars", status: "ON", balance: 124.66, currency: "USD" },
  { vps: "VPS 1", booker: "1win", status: "ON", balance: 143.35, currency: "USDT" },
  { vps: "VPS 1", booker: "Melbet", status: "ON", balance: 508.74, currency: "USD" },
  { vps: "VPS 1", booker: "BetFury", status: "ON", balance: 14.22, currency: "USDT" },
  { vps: "VPS 1", booker: "Gamdom", status: "ON", balance: 4.71, currency: "USD" },
  { vps: "VPS 2", booker: "Pinnacle", status: "ON", balance: 222.56, currency: "USD" },
  { vps: "VPS 2", booker: "PokerStars", status: "ON", balance: 211.8, currency: "USD" },
  { vps: "VPS 2", booker: "BetFury", status: "ON", balance: 25.63, currency: "USDT" },
  { vps: "VPS 2", booker: "Shuffle", status: "ON", balance: 3.07, currency: "USDT" },
  { vps: "VPS 2", booker: "Polymarket", status: "ON", balance: 38.29, currency: "USDT" },
  { vps: "VPS 2", booker: "Sportsbetio", status: "ON", balance: 512.51, currency: "USDT" },
  { vps: "VPS 2", booker: "Kalshi", status: "ON", balance: 2.38, currency: "USDT" },
  { vps: "VPS 2", booker: "ArtLine", status: "ON", balance: 0.22, currency: "USDT" },
  { vps: "VPS 2", booker: "Gamdom", status: "ON", balance: 34.27, currency: "USD" },
  { vps: "VPS 2", booker: "BC.Game", status: "ON", balance: 123.52, currency: "USD" },
  { vps: "VPS 2", booker: "Betdex", status: "ON", balance: 119.99, currency: "USD" },
  { vps: "VPS 2", booker: "Vavada", status: "ON", balance: 303, currency: "USD" },
  { vps: "VPS 2", booker: "888sport", status: "ON", balance: 115.4, currency: "USD" },
  { vps: "VPS 2", booker: "BetOnline", status: "ON", balance: 39.82, currency: "USD" },
  { vps: "VPS 2", booker: "Cloudbet", status: "ON", balance: 124.58, currency: "USDT" },
  { vps: "VPS 3", booker: "1win", status: "ON", balance: 1.67, currency: "USDT" },
  { vps: "VPS 3", booker: "Melbet", status: "ON", balance: 66.38, currency: "USDT" },
  { vps: "VPS 3", booker: "BetFury", status: "ON", balance: 455, currency: "USDT" },
  { vps: "VPS 3", booker: "Gamdom", status: "ON", balance: 3.85, currency: "USD" },
  { vps: "VPS 3", booker: "BetOnline", status: "OFF", balance: 0, currency: "USD", note: "Internal Error | Betonline" },
  { vps: "VPS 3", booker: "ArtLine", status: "ON", balance: 345.04, currency: "USDT" },
  { vps: "VPS 4", booker: "1xBit", status: "ON", balance: 140.91, currency: "USDT" },
  { vps: "VPS 4", booker: "1win", status: "ON", balance: 2.13, currency: "USDT" },
  { vps: "VPS 4", booker: "Gamdom", status: "ON", balance: 280.41, currency: "USD", note: "BOOKER_CIRCUIT_OPEN: vps4/gamdom falló 2 arbs distintos; no se enviarán más apuestas" },
  { vps: "VPS 4", booker: "BC.Game", status: "ON", balance: 72.23, currency: "USD" },
  { vps: "VPS 4", booker: "BetOnline", status: "ON", balance: 81.4, currency: "USD" },
  { vps: "VPS 4", booker: "Kalshi", status: "PRE MARKET", balance: 0, currency: "USDT" },
  { vps: "VPS 4", booker: "Polymarket", status: "PRE MARKET", balance: 0, currency: "USDT" },
  { vps: "VPS 4", booker: "SXBET", status: "PRE MARKET", balance: 0, currency: "USDT" },
  { vps: "VPS 2", booker: "Jackbit", status: "ON", balance: 180.5, currency: "USDT" },
  { vps: "VPS 2", booker: "Jack", status: "OFF", balance: 0, currency: "USDT" },
  { vps: "VPS 5", booker: "1xBet", status: "ON", balance: 0, currency: "USD" },
  { vps: "VPS 5", booker: "1win", status: "ON", balance: 0, currency: "USDT" },
  { vps: "VPS 5", booker: "Jack", status: "ON", balance: 136, currency: "USDT.ERC20" },
  { vps: "VPS 5", booker: "Sportsbetio", status: "OFF", balance: 0, currency: "USDT", note: "Falta sportsbetio.cookie/cookies o SPORTSBETIO_COOKIE para consultar balance" },
  { vps: "VPS 5", booker: "BetFury", status: "BLK", balance: 0, currency: "USDT", note: "BetFury no pudo obtener el saldo de la cuenta mediante CDP" },
  { vps: "VPS 5", booker: "Stake", status: "ON", balance: 117.29, currency: "USD" }
].map((account) => ({
  ...account,
  id: `${account.vps}-${account.booker}`.toLowerCase().replace(/[^a-z0-9]+/g, "-")
}));

export const ACTIVE_CLIENT_COUNT = CLIENT_ACCOUNTS.filter(
  (account) => account.status === "ON"
).length;
