export const CLIENT_ACCOUNTS = [
  { vps: "VPS 1", booker: "PokerStars", status: "ON", balance: 131.07, currency: "USD" },
  { vps: "VPS 1", booker: "1win", status: "ON", balance: 133.42, currency: "USDT" },
  { vps: "VPS 1", booker: "Melbet", status: "ON", balance: 515.15, currency: "USD" },
  { vps: "VPS 1", booker: "BetFury", status: "ON", balance: 22.78, currency: "USDT" },
  { vps: "VPS 1", booker: "Gamdom", status: "ON", balance: 376.04, currency: "USD" },
  { vps: "VPS 2", booker: "Pinnacle", status: "ON", balance: 130.07, currency: "USD" },
  { vps: "VPS 2", booker: "PokerStars", status: "ON", balance: 555.31, currency: "USD" },
  { vps: "VPS 2", booker: "BetFury", status: "ON", balance: 8.11, currency: "USDT" },
  { vps: "VPS 2", booker: "Shuffle", status: "ON", balance: 9.47, currency: "USDT" },
  { vps: "VPS 2", booker: "Polymarket", status: "ON", balance: 19.99, currency: "USDT" },
  { vps: "VPS 2", booker: "Sportsbetio", status: "ON", balance: 218.8, currency: "USDT" },
  { vps: "VPS 2", booker: "Kalshi", status: "ON", balance: 168.67, currency: "USDT" },
  { vps: "VPS 2", booker: "ArtLine", status: "ON", balance: 26.74, currency: "USDT" },
  { vps: "VPS 2", booker: "Gamdom", status: "ON", balance: 35.64, currency: "USD" },
  { vps: "VPS 2", booker: "BC.Game", status: "ON", balance: 129.92, currency: "USD" },
  { vps: "VPS 2", booker: "Betdex", status: "ON", balance: 126.39, currency: "USD" },
  { vps: "VPS 2", booker: "Vavada", status: "ON", balance: 44.21, currency: "USD" },
  { vps: "VPS 2", booker: "888sport", status: "ON", balance: 107.4, currency: "USD" },
  { vps: "VPS 2", booker: "BetOnline", status: "ON", balance: 46.22, currency: "USD" },
  { vps: "VPS 2", booker: "Cloudbet", status: "ON", balance: 130.98, currency: "USDT" },
  { vps: "VPS 3", booker: "1win", status: "ON", balance: 141.62, currency: "USDT" },
  { vps: "VPS 3", booker: "Melbet", status: "ON", balance: 72.78, currency: "USDT" },
  { vps: "VPS 3", booker: "BetFury", status: "ON", balance: 23.2, currency: "USDT" },
  { vps: "VPS 3", booker: "Gamdom", status: "ON", balance: 146.11, currency: "USD" },
  { vps: "VPS 3", booker: "BetOnline", status: "OFF", balance: 0, currency: "USD", note: "Internal Error | Betonline" },
  { vps: "VPS 3", booker: "ArtLine", status: "ON", balance: 39.4, currency: "USDT" },
  { vps: "VPS 4", booker: "1xBit", status: "ON", balance: 179.29, currency: "USDT" },
  { vps: "VPS 4", booker: "1win", status: "ON", balance: 267.76, currency: "USDT" },
  { vps: "VPS 4", booker: "Gamdom", status: "ON", balance: 456.53, currency: "USD" },
  { vps: "VPS 4", booker: "BC.Game", status: "ON", balance: 78.63, currency: "USD" },
  { vps: "VPS 4", booker: "BetOnline", status: "ON", balance: 73.4, currency: "USD" },
  { vps: "VPS 4", booker: "Kalshi", status: "PRE MARKET", balance: 0, currency: "USDT" },
  { vps: "VPS 4", booker: "Polymarket", status: "PRE MARKET", balance: 0, currency: "USDT" },
  { vps: "VPS 4", booker: "SXBET", status: "PRE MARKET", balance: 0, currency: "USDT" },
  { vps: "VPS 2", booker: "Jackbit", status: "ON", balance: 172.5, currency: "USDT" },
  { vps: "VPS 2", booker: "Jack", status: "OFF", balance: 0, currency: "USDT" },
  { vps: "VPS 5", booker: "1xBet", status: "OFF", balance: 0, currency: "USDT" },
  { vps: "VPS 5", booker: "1win", status: "OFF", balance: 0, currency: "USDT" },
  { vps: "VPS 5", booker: "Jack", status: "OFF", balance: 0, currency: "USDT" },
  { vps: "VPS 5", booker: "Sportsbetio", status: "OFF", balance: 0, currency: "USDT" },
  { vps: "VPS 5", booker: "BetFury", status: "ON", balance: 106.4, currency: "USDT" },
  { vps: "VPS 5", booker: "Stake", status: "OFF", balance: 0, currency: "USDT" }
].map((account) => ({
  ...account,
  id: `${account.vps}-${account.booker}`.toLowerCase().replace(/[^a-z0-9]+/g, "-")
}));

export const ACTIVE_CLIENT_COUNT = CLIENT_ACCOUNTS.filter(
  (account) => account.status === "ON"
).length;
