export const WITHDRAWALS = [
  {
    "id": "crypto-deposit-2026-05-24",
    "movementType": "Depósito",
    "bookmaker": "Crypto",
    "vps": "Cuenta principal",
    "date": "2026-05-24",
    "amount": 300,
    "currency": "USDT",
    "status": "Registrado"
  },
  {
    "id": "crypto-deposit-2026-06-19",
    "movementType": "Depósito",
    "bookmaker": "Crypto",
    "vps": "Cuenta principal",
    "date": "2026-06-19",
    "amount": 500,
    "currency": "USDT",
    "status": "Registrado"
  },
  {
    "id": "crypto-deposit-2026-06-20",
    "movementType": "Depósito",
    "bookmaker": "Crypto",
    "vps": "Cuenta principal",
    "date": "2026-06-20",
    "amount": 2600,
    "currency": "USDT",
    "status": "Registrado"
  },
  {
    "id": "crypto-deposit-2026-06-28",
    "movementType": "Depósito",
    "bookmaker": "Crypto",
    "vps": "Cuenta principal",
    "date": "2026-06-28",
    "amount": 500,
    "currency": "USDT",
    "status": "Registrado"
  },
  {
    id: "pokerstars-2026-08-06",
    movementType: "Retiro",
    bookmaker: "PokerStars",
    vps: "VPS 2",
    date: "2026-08-06",
    amount: 500,
    receivedAmount: 457.81,
    currency: "USDT",
    approximateMxn: 7917.63,
    address: "0xcc83...b1874e",
    network: "Ethereum",
    estimatedTime: "Aprox. 15 min.",
    exchangeRate: "1 USDT = 17.29469 MXN",
    exchangeFeeMxn: 118.79,
    transactionFeeMxn: 164.05,
    networkFeeMxn: 1.89,
    totalSpentMxn: 8202.36,
    status: "Completado",
    receiptImage: "/withdrawals/pokerstars-2026-08-06.png"
  },
  {
    id: "gamdom-vps4-2026-08-10",
    movementType: "Retiro",
    bookmaker: "Gamdom",
    vps: "VPS 4",
    date: "2026-08-10",
    amount: 200,
    receivedAmount: 200,
    currency: "MXN",
    status: "Completado",
    receiptImage: "/withdrawals/gamdom-vps4-2026-08-10.png"
  },
  {
    id: "vps5-payment-2026-08-10",
    movementType: "Pago",
    bookmaker: "Pago de VPS",
    vps: "VPS 5",
    date: "2026-08-10",
    amount: 20,
    currency: "USD",
    status: "Pendiente",
    receiptImage: "/withdrawals/vps5-payment-2026-08-10.jpg"
  },
  {
    id: "crypto-deposit-2026-08-11",
    movementType: "Depósito",
    bookmaker: "Crypto",
    vps: "Cuenta principal",
    date: "2026-08-11",
    amount: 500,
    currency: "USDT",
    status: "Completado"
  },
  {
    id: "gamdom-vps1-2026-08-12",
    movementType: "Retiro",
    bookmaker: "Gamdom",
    vps: "VPS 1",
    date: "2026-08-12",
    amount: 199.97,
    receivedAmount: 200.13,
    currency: "USD",
    receivedCurrency: "USDT",
    status: "Enviado",
    receiptImage: "/withdrawals/gamdom-vps1-2026-08-12.png"
  },
  {
    id: "gamdom-vps4-2026-08-12",
    movementType: "Retiro",
    bookmaker: "Gamdom",
    vps: "VPS 4",
    date: "2026-08-12",
    amount: 249.95,
    receivedAmount: 250.15,
    currency: "USD",
    receivedCurrency: "USDT",
    status: "Confirmado",
    receiptImage: "/withdrawals/gamdom-vps4-2026-08-12.png"
  },
  {
    id: "vavada-vps2-2026-08-13",
    movementType: "Retiro",
    bookmaker: "Vavada",
    vps: "VPS 2",
    date: "2026-08-13",
    amount: 380,
    receivedAmount: 380,
    currency: "USDT",
    receivedCurrency: "USDT-ERC20",
    status: "Completado",
    receiptImage: "/withdrawals/vavada-vps2-2026-08-13.png"
  },
  {
    "id": "income-2026-09-10",
    "movementType": "Depósito",
    "bookmaker": "Ingreso",
    "vps": "Cuenta principal",
    "date": "2026-09-10",
    "amount": 3400,
    "currency": "USD",
    "status": "Registrado"
  },
  {
    "id": "vps1-payment-2026-09-10",
    "movementType": "Pago",
    "bookmaker": "Pago de VPS",
    "vps": "VPS 1",
    "date": "2026-09-10",
    "amount": 25,
    "currency": "USD",
    "status": "Registrado"
  },
  {
    "id": "vps2-payment-2026-09-10",
    "movementType": "Pago",
    "bookmaker": "Pago de VPS",
    "vps": "VPS 2",
    "date": "2026-09-10",
    "amount": 25,
    "currency": "USD",
    "status": "Registrado"
  },
  {
    "id": "vps3-payment-2026-09-10",
    "movementType": "Pago",
    "bookmaker": "Pago de VPS",
    "vps": "VPS 3",
    "date": "2026-09-10",
    "amount": 25,
    "currency": "USD",
    "status": "Registrado"
  },
  {
    "id": "vps4-payment-2026-09-10",
    "movementType": "Pago",
    "bookmaker": "Pago de VPS",
    "vps": "VPS 4",
    "date": "2026-09-10",
    "amount": 25,
    "currency": "USD",
    "status": "Registrado"
  },
  {
    "id": "vps5-payment-2026-09-10",
    "movementType": "Pago",
    "bookmaker": "Pago de VPS",
    "vps": "VPS 5",
    "date": "2026-09-10",
    "amount": 25,
    "currency": "USD",
    "status": "Registrado"
  },
  {
    "id": "vps6-payment-2026-09-10",
    "movementType": "Pago",
    "bookmaker": "Pago de VPS",
    "vps": "VPS 6",
    "date": "2026-09-10",
    "amount": 25,
    "currency": "USD",
    "status": "Registrado"
  },
  {
    "id": "vps7-payment-2026-09-10",
    "movementType": "Pago",
    "bookmaker": "Pago de VPS",
    "vps": "VPS 7",
    "date": "2026-09-10",
    "amount": 25,
    "currency": "USD",
    "status": "Registrado"
  },
  {
    "id": "arg-account-payment-2026-09-10",
    "movementType": "Pago",
    "bookmaker": "Cuenta ARG",
    "vps": "Cuenta ARG",
    "date": "2026-09-10",
    "amount": 100,
    "currency": "USD",
    "status": "Registrado"
  },
  {
    "id": "three-vps-payment-2026-09-17",
    "movementType": "Pago",
    "bookmaker": "Pago de 3 VPS",
    "vps": "3 VPS",
    "date": "2026-09-17",
    "amount": 75,
    "currency": "USD",
    "status": "Registrado"
  },
  {
    "id": "crypto-deposit-2026-09-27",
    "movementType": "Depósito",
    "bookmaker": "Crypto",
    "vps": "Cuenta principal",
    "date": "2026-09-27",
    "amount": 750,
    "currency": "USDT",
    "status": "Registrado"
  },
  {
    "id": "two-clients-payment-2026-10-03",
    "movementType": "Pago",
    "bookmaker": "Pago de 2 clientes",
    "vps": "2 clientes",
    "date": "2026-10-03",
    "amount": 360,
    "currency": "USDT",
    "status": "Registrado"
  },
  {
    "id": "ivan-week-payment-2026-10-03",
    "movementType": "Pago",
    "bookmaker": "Semana Iván",
    "vps": "Iván",
    "date": "2026-10-03",
    "amount": 168,
    "currency": "USDT",
    "status": "Registrado"
  },
  {
    "id": "two-vps-payment-2026-10-05",
    "movementType": "Pago",
    "bookmaker": "Pago de 2 VPS",
    "vps": "2 VPS",
    "date": "2026-10-05",
    "amount": 50,
    "currency": "USDT",
    "status": "Registrado"
  }
];
